[package]

name = "strenum"
version = "0.0.6"
authors = ["Igor Polyakov <iopguy@gmail.com>"]
description = "An enum that can print all of its variants"
repository = "https://github.com/iopq/strenum"
license = "MIT"

[dependencies]
enum_primitive = "*"
num = "*"